name: Running Tests with Pest

on: [push]

jobs:
  pest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3
          tools: composer:v2
          coverage: xdebug

      - name: Install composer dependencies
        uses: ramsey/composer-install@v3

      - name: Set up Laravel environment
        run: cp .env.testing .env

      # - uses: ryohidaka/action-setup-sqlite@v1.2.0
      #   with:
      #     version: "3.43.2"

      - name: Run migrations
        run: php artisan migrate --env=testing

      - name: Tests
        run: ./vendor/bin/pest --ci
